### PR TITLE
aes: fix build errors

### LINKED ISSUE #263: Build error: in compatibility with hmac change
The [Cargo.toml](https://github.com/containers/ocicrypt-rs/blob/9af596112a64326828416806e049cf0e0ffc9320/Cargo.toml#L31) states that it supports `hmac` `">=0.11"`, but it is using the [`NewMac` trait](https://docs.rs/hmac/0.11.0/hmac/trait.NewMac.html) that has been removed in `v0.12.0`.

This results in the error:
```
error[E0432]: unresolved import `hmac::NewMac`
 --> src/blockcipher/aes_ctr.rs:8:23
  |
8 | use hmac::{Hmac, Mac, NewMac};
  |                       ^^^^^^ no `NewMac` in the root

error[E0308]: mismatched types
  --> src/blockcipher/aes_ctr.rs:54:41
   |
54 |                     hmac.clone().verify(&self.exp_hmac).map_err(|_| {
   |                                         ^^^^^^^^^^^^^^ expected struct `GenericArray`, found struct `Vec`
   |
   = note: expected reference `&GenericArray<u8, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>`
              found reference `&Vec<u8>`

Some errors have detailed explanations: E0308, E0432.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `ocicrypt-rs` due to 2 previous errors
```
when running `cargo build --all-features`

Whether the trait should have been removed from a version change `0.11` to `0.12` is another issue, but in the mean time it would be good to fix up the build here.

### PR DESCRIPTION
**Pull request by stevenhorsman**
Updates the hmac version requirements and code to fix the build errors

Fixes: confidential-containers/guest-components#263
Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### CODE REVIEW

**Comment by stevenhorsman** [comment]
Hey @arronwy - this issue is causing problems in the kata-agent CCv0 build due to the dependency on this repo for the `rustified` pull image (e.g. the static checks failing in https://github.com/kata-containers/kata-containers/pull/3377). I may have got the fix wrong here, but it would be great if you could have a look and let me know. Thanks!

**Comment by sameo** [comment]
Hey @stevenhorsman . Thanks for the PR...Running the GH actions now, let's see.

**Comment by stevenhorsman** [comment]
@sameo - thanks for kicking off the workflow. There were a bunch of nightly clippy errors. None of it in code I changed, but I've fixed up most of them. There was one error in `src/utils/keyprovider.rs` which I could fix as I think that file is generated and I've not got much experience with proto buffers to know how to add annotations.

**Comment by stevenhorsman** [comment]
Hi @arronwy - are you able to help with the final linting problem? Thanks.

**Comment by arronwy** [comment]
> Hi @arronwy - are you able to help with the final linting problem? Thanks.

Sure, I'll be back to office tomorrow and check this issue with @pravinrajr9

**Comment by pravinrajr9** [comment]
> > Hi @arronwy - are you able to help with the final linting problem? Thanks.
> 
> Sure, I'll be back to office tomorrow and check this issue with @pravinrajr9

utils/keyprovider.rs is auto generated code, there is a issue opened here https://github.com/hyperium/tonic/issues/876 has an open issue
we might to wait or we might need to stop generating this code from build.rs and fix manually with the patch below

`diff --git a/src/utils/keyprovider.rs b/src/utils/keyprovider.rs
index d12ce43..c481f8e 100644
--- a/src/utils/keyprovider.rs
+++ b/src/utils/keyprovider.rs
@@ -59,11 +59,13 @@ pub mod key_provider_service_client {
         #[doc = r""]
         #[doc = r" This requires the server to support it otherwise it might respond with an"]
         #[doc = r" error."]
+        #[must_use]
         pub fn send_gzip(mut self) -> Self {
             self.inner = self.inner.send_gzip();
             self
         }
         #[doc = r" Enable decompressing responses with `gzip`."]
+        #[must_use]
         pub fn accept_gzip(mut self) -> Self {
             self.inner = self.inner.accept_gzip();
             self
`

**Comment by stevenhorsman** [comment]
@pravinrajr9 - thanks for the information and link. Given that the tonic issue hasn't been looked at for 12 days and this PR has been holding up work in kata-containers for 8 days it would be great to get a workaround in with the patch you suggested.

**Comment by arronwy** [comment]
@sameo Since the clippy error happens on nightly build aganist auto generated code, can we merged this PR first and wait tonic upstream to fix the issue to avoid the temp fix in our repo?

**Comment by sameo** [comment]
> @sameo Since the clippy error happens on nightly build aganist auto generated code, can we merged this PR first and wait tonic upstream to fix the issue to avoid the temp fix in our repo?

@arronwy I'd prefer if we carry @pravinrajr9 patch and disable the autogenerated code until https://github.com/hyperium/tonic/pull/892 is merged.

**Comment by sameo** [comment]
@arronwy @stevenhorsman @pravinrajr9 Build is fixed with a couple of fixes. Are you ok with merging it?

**Review by arronwy — APPROVED** [review]
lgtm, thanks @stevenhorsman @sameo

**Review by pravinrajr9 — APPROVED** [review]
LGTM

**Pull request merged**
